# Generated by Django 3.2.6 on 2021-08-26 00:34

import FireDevsApp.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
            ],
            options={
                'db_table': 'pais',
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
            ],
            options={
                'db_table': 'sexo',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('capacity', models.IntegerField(default=30, verbose_name='Capacidad')),
            ],
            options={
                'db_table': 'grupo',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
            ],
            options={
                'db_table': 'persona',
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='FireDevsApp.person')),
            ],
            options={
                'db_table': 'profesor',
            },
            bases=('FireDevsApp.person',),
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='FireDevsApp.country', verbose_name='País')),
            ],
            options={
                'db_table': 'ciudad',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='FireDevsApp.person')),
                ('bornDate', models.DateField(validators=[FireDevsApp.validators.MinAgeValidator(18), FireDevsApp.validators.MaxAgeValidator(27)], verbose_name='Fecha de nacimiento')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('bornCity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='FireDevsApp.city', verbose_name='Ciudad de nacimiento')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='FireDevsApp.gender', verbose_name='Sexo')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='FireDevsApp.group', verbose_name='Grupo')),
            ],
            options={
                'db_table': 'estudiante',
            },
            bases=('FireDevsApp.person',),
        ),
        migrations.AddField(
            model_name='group',
            name='main_professor',
            field=models.ForeignKey(on_delete=models.Model, to='FireDevsApp.professor'),
        ),
    ]
